vo=gpu-next
hwdec=auto-safe
profile=gpu-hq

osc=yes
osd-scale-by-window=no

# Matte look: remove transparency & glow
border=no
osd-color="#e0e0e0"
osd-border-color="#5a0a0b"
osd-border-size=1
osd-shadow-color="#5a0a0b"
osd-shadow-size=1