


# Preload all wallpapers
preload = ~/Wallpapers/*

# Default wallpaper (on startup)
#wallpaper = ,~/Wallpapers/default.jpg

# If you have second monitor, add:
wallpaper = HDMI-A-1,~/Wallpapers/default.jpg

splash = false
