source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/defaults.conf


################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,1

#####################
### LOOK AND FEEL ###
#####################
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 3

 
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    col.active_border = rgba(ff000099)
  
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 8
    rounding_power = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = false
        range = 20
        render_power = 10
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 6
        passes = 3
        
        new_optimizations = true
        popups = true        # blur menus/popups too
        special = true       # blur special windows
        vibrancy = 0.1696
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
source = ~/.config/hypr/animations.conf
# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

misc {
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
env = HYPRSHOT_DIR,/home/grey/Pictures/Screenshots
