##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev2 = float, title:^(Wallpaper Picker)$
windowrulev2 = center, title:^(Wallpaper Picker)$
windowrulev2 = size 1000 600, title:^(Wallpaper Picker)$

windowrulev2 = float, title:^(Open Files)$
windowrulev2 = center, title:^(Open Files)$
windowrulev2 = size 900 600, title:^(Wallpaper Picker)$

windowrulev2 = float, class:Pacseek
windowrulev2 = center, class:Pacseek
windowrulev2 = size 900 600, class:Pacseek

### BLUETOOTH MANAGER ###
windowrule = float, class:^(blueman-manager)$
windowrule = center, class:^(blueman-manager)$
windowrule = size 700 550, class:^(blueman-manager)$


### PAVUCONTROL ###
windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = center, class:^(org.pulseaudio.pavucontrol)$
windowrule = size 700 840, class:^(org.pulseaudio.pavucontrol)$


### BTOP USING KITTY ###
# matches any kitty window with title btop
windowrule = float, class:^(kitty)$, title:^(btop)$
windowrule = center, class:^(kitty)$, title:^(btop)$
windowrule = size 900 600, class:^(kitty)$, title:^(btop)$


### NMTUI as floating dialog ###
windowrulev2 = float,  class:^(nmtui)$
windowrulev2 = center, class:^(nmtui)$
windowrulev2 = size 900 750, class:^(nmtui)$

