########################################
# Autostart (for this rice)
########################################

# Wallpaper daemon (Hyprpaper, Path A)
exec-once = hyprpaper

# Bar
exec-once = waybar

# Notifications
exec-once = dunst

# Network applet (if you use NetworkManager)
exec-once = nm-applet

# Polkit agent (for auth dialogs)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
