# --- DECORATION (MATTE) ---
decoration {
    rounding = 6

    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = false
    shadow_range = 0
    shadow_render_power = 0

    blur = false

    blur_strength = 0

    border_size = 2
    border_color_active = 0xFF3B4252
    border_color_inactive = 0xFF2E3440

    titlebar_height = 28
    titlebar_font = "Fira Sans Medium"
    titlebar_font_size = 12
    titlebar_color_active = 0xFF4C566A
    titlebar_color_inactive = 0xFF3B4252
}