##############################
# Hyprland Main Config (Split)
##############################

# Theme (matte for now, transparent later)
source = ~/.config/hypr/colors-matte.conf

# Config split modules
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/cursor.conf


### extras ###

env = QT_QPA_PLATFORMTHEME,kvantum
