# --- TILING LAYOUT (DWINDLE) ---
dwindle {
    pseudotile = yes
    preserve_split = yes
    no_gaps_when_only = false
}

# --- GENERAL LAYOUT ---
general {
    gaps_in = 8
    gaps_out = 16

    border_size = 2

    col.active_border   = $accent_dark
    col.inactive_border = $border

    layout = dwindle
}
