# Straight 1x setup for low-resolution displays like 1080p or 1440p
env = GDK_SCALE,1
monitor=,preferred,auto,1


# For high-DPI displays like 4K, uncomment the following lines and comment the above two lines
# env = GDK_SCALE,2
# monitor=,preferred,auto,2             