# ----- THEME: Red Black -----
theme[main_bg]="#000000"
theme[main_fg]="#ffffff"

theme[title]="#ff3737"
theme[hi_fg]="#ff3737"

theme[div_fg]="#1a1a1a"
theme[div_bg]="#000000"

theme[stat_bg]="#050505"
theme[stat_fg]="#eaeaea"

theme[selected_bg]="#111111"
theme[selected_fg]="#ff3737"

theme[highlight]="#ff3737"

# Graph colors
theme[cpu_graph_high]="#ff3737"
theme[cpu_graph_low]="#660000"

theme[mem_graph_high]="#ff3737"
theme[mem_graph_low]="#550000"

theme[disk_graph_high]="#ff3737"
theme[disk_graph_low]="#440000"

# Processes
theme[proc_misc]="#ff3737"
theme[proc_box]="#000000"
theme[proc_box_hi]="#ff3737"
theme[proc_box_title]="#ff3737"
theme[proc_selected]="#ff3737"

# Net
theme[net_box]="#000000"
theme[net_box_hi]="#ff3737"

# Temperature
theme[temp_cold]="#999999"
theme[temp_hot]="#ff3737"

