# ----- THEME: Red Dark -----
theme[main_bg]="#0a0a0a"
theme[main_fg]="#f2f2f2"

theme[title]="#ff3737"
theme[hi_fg]="#ff3737"

theme[div_fg]="#2e2e2e"
theme[div_bg]="#0a0a0a"

theme[stat_bg]="#141414"
theme[stat_fg]="#dcdcdc"

theme[selected_bg]="#1b1b1b"
theme[selected_fg]="#ff3737"

theme[highlight]="#ff3737"

# Graph colors
theme[cpu_graph_high]="#ff3737"
theme[cpu_graph_low]="#992222"

theme[mem_graph_high]="#ff3737"
theme[mem_graph_low]="#772222"

theme[disk_graph_high]="#ff3737"
theme[disk_graph_low]="#552222"

# Processes
theme[proc_misc]="#ff3737"
theme[proc_box]="#1c1c1c"
theme[proc_box_hi]="#ff3737"
theme[proc_box_title]="#ff3737"
theme[proc_selected]="#ff3737"

# Net
theme[net_box]="#1c1c1c"
theme[net_box_hi]="#ff3737"

# Temperature
theme[temp_cold]="#888888"
theme[temp_hot]="#ff3737"
